### ISSUE TITLE
Markdown Annotations

### ISSUE THREAD

**Issue by boulderob** [chrisrzhou/unified-doc#2]
Hello.  I just stumbled on this project by accident today.  Nice work!  Some implementation questions if you have time.  Mind you my React skills are lacking.  

1) Your examples are excellent but an additional one with serialization to a back end might be helpful if you can get around to it.   I probably need to wrap my head around the simpler flat file  data sources you are pulling in at build time.  But I'm trying to envision how to persist the annotations to a back end, then retrieve them later to "superimpose"  or "playback" on top of the original and separate html document.  Basically I'm wondering if it's possible to keep the original "clean" html source file separate as master, update and maintain separate annotations over time and then always just "apply" or "play them back"  over the clean source?   That hopefully should make sense.

2) I see how you insert physical mark tags into the html to indicate visual styling of an annotation and tie positioning of related text to it (on hover, click, etc).  So there's tight binding there.  Let's say I store my page src as markdown though which is later parsed to html for page rendering.   Is there a way to **directly** save / persist the annotations (positioning and related text) with respect to **or in** the original markdown document?  I can't tell if this is functionality is provided or not with your code but it appears that rendering markdown to HTML first is going to always be a prerequisite because markdown doesn't natively know how to tie   positioning to annotations.

3) I tried an example whereby I created overlapping annotations by creating one on top of another existing one and it looks like it worked which is pretty cool!  The question I have is when you select drag with the mouse, even more so when the select is overlapping, how does your code successfully insert the mark tags so that they don't straddle (aka interrupt or break up) an existing  pair of html tags?  When you mouse select on the browser screen I don't think that there's any guarantee that you are selecting the correct underlying html structure to prevent what i just described.   Basically I'm curious if you can point to where in your code this handling takes place or if you could point me to some key words / links to search and read about how it's handled?  Perhaps there's also no way to do this!

Regardless.  Nice Work!

**Comment by chrisrzhou** [comment]
Hi thanks for checking out the project! I'm in the process of cleaning up some of the packages and updating the docs.  This project started out fairly new and raw and there's a better sense around how to structure the various packages.  Be on the lookout for `v1` which will reduce the number of packages and have useful methods that `unified-doc` will export that provides unified interfaces for working with documents.

It's a little hard to fully grasp your concerns so I'll try my best to address them:

1. `unified-doc` doesn't care about how you relate a source file with annotations.  The idea I would do in your case is to have some method that generates annotation based on the source content (i.e. the `html/markdown/text` file).  Annotation offsets work against the **source** content.  So if your content is markdown, your algorithm that generates the offsets should be based off this content.  Once generated, you can choose to save the annotations in relation to the source content in a relational DB or loosely pair it NoSQL store.  It's a good idea to keep annotations in relation to their source content, since that is how they are generated in the first place.  If the source content changes, the annotations won't be meaningful since the offsets are related to the content it was referring to.

2. Annotations don't actually affect the source content.  They are stored as separate `annotations` object.  They actually relate to the source content, so if your source content is `markdown`, the offsets of the annotations are only meaningful against the `markdown` source content string, and not the evaluated HTML.  The `mark` tags are inserted after the markdown has been turned in to a `hast` tree, and into HTML.  The output will always be HTML because that will allow us to use downstream web technologies to continue working on the cdocument.

3. This was pretty fun to build and took the longest to figure out how to support a way to perform overlapping annotations.  It's not the best algorithm, but it seems to work based on the needs of the project.  There's two parts to this problem:
  1. Creating (overlapping annotations).  This algorithm is done against the `hast` tree and is found in https://github.com/chrisrzhou/unified-doc/blob/master/packages/hast-util-annotate/src/index.js.  I'm not great at algorithms (no CS background), but this was organically implemented after a few failed iterations.  It might not be explicitly clear in the code but hope you can somewhat follow it.  The general idea here is for a given annotation (`startOffset`, `endOffset`), you break up all the text nodes into snippets.  Two annotations overlapping each other will have at most 3 parts and so on.  Then wrap each snippet with the associated annotation data that's provided.
  2. The actual act of selecting text to create annotations.  The selection code is found in: https://github.com/chrisrzhou/unified-doc/blob/master/packages/react-unified-doc/src/select-text.js.  The general idea here is to be able to associate the selected text against the source offsets.  These source offsets are extracted by `https://github.com/chrisrzhou/unified-doc/tree/master/packages/hast-util-extract-text-offsets` which maps text-based offsets against the source-content text offsets.  With this mapping, you can reverse-calculate the source offsets and with the source offsets, you can create an annotation.

I'm in the process of reorganizing the project and a lot of these features will be better organized as utility methods in a core `unified-doc` package that will export `select-text` method, which can be useful as a method even outside of the project.

I expect to finish most of the refactoring/rework this weekend or next weekend.

Thanks and hope this helps!

**Comment by boulderob** [comment]
@chrisrzhou Thanks for the reply.

I'm going to have to explore #3 on my own with the additional information you gave me.   

Regarding #1 and #2.

I think what you're telling me is that this is going to do exactly what I want it to do.  :)    I'm going to clone your examples (which all seem to use pure html as source) and **replace the reference in src/data to "alice in wonderland" with pure markdown**.    That should display pure markdown on the webpage.   I'll try to drag annotate and If they work exactly the same then then I will have *seen the light* so to speak ;)

I think the disconnect I'm having is that I'm not used to seeing a live js markdown parser on a webpage create an AST in real-time where the user can visually interact with it by selecting on the web page.  If what i'm saying is true that would allow something like unified-doc to actually attach annotations **directly to markdown on a webpage** which normally wouldn't be possible.  Normally you would have to render the markdown as html first and THEN use js to annotate the rendered HTML / DOM (ie not the AST).   It's a paradigm shift which is why it is a little hard to grasp.  

If you have anything else to enlighten feel free.  I'll do what i suggested above in the meantime.  

Thanks!

**Comment by boulderob** [comment]
hey @chrisrzhou, fyi,  i tried rebuilding after making the changes i suggested above but it's breaking:  on a fresh clone started with `npm install` followed by  `npm run build` (also tried `yarn run build`)and it's breaking.  i'll revisit this tomorrow.

**Comment by chrisrzhou** [comment]
Hi @boulderob, active development of the project is now maintained in the [unified-doc](https://github.com/unified-doc) org.

There are some changes to the core APIs and better separation of concerns for APIs/wrappers/DOM-methods.  In general, they should be an improvement to what was initially explored in this project/repo.  Feel free to check it out.
